export const IMAGES = {
  BUS: require("../../assets/logo.png"),
  ONBOARDING1: require("../../assets/onboarding1.png"),
  ONBOARDING2: require("../../assets/onboarding2.png"),
  ONBOARDING3: require("../../assets/onboarding3.png"),
  OFFER1: require("../../assets/offer1.png"),
  OFFER2: require("../../assets/offer2.png"),
  OFFER3: require("../../assets/offer3.png"),
  OFFER4: require("../../assets/offer4.png"),
  AXIS: require("../../assets/axislogo.png"),
  HDFC: require("../../assets/HDFClogo.png"),
  CHATBOT: require("../../assets/chatbot.png"),
  IDBI: require("../../assets/IDBIlogo.png"),
  OFFER6: require("../../assets/offers/offer6.png"),
  OFFER7: require("../../assets/offers/offer1.png"),
  OFFER8: require("../../assets/offers/offer2.png"),
  OFFER9: require("../../assets/offers/offer3.png"),
  OFFER10: require("../../assets/offers/offer4.png"),
  REFER: require("../../assets/refer.png"),
  WALLET: require("../../assets/wallet.png"),
  WALLET_EMPTY: require("../../assets/wallet1.png"),
  BUS1: require("../../assets/bus1.png"),
  BUS2: require("../../assets/bus2.png"),
  STUDENT: require("../../assets/Student.png"),
  NO_BOOKING: require("../../assets/no-booking.png"),
  OTP: require("../../assets/otp2.png"),
  PHONEPAY: require("../../assets/Bank/Ppay.png"),
  GOOGLEPAY: require("../../assets/Bank/GPay.png"),
  AMAZONPAY: require("../../assets/Bank/Apay.png"),
  CANARA: require("../../assets/Bank/Canara.png"),
  ICICI: require("../../assets/Bank/ICICI.png"),
  SBI: require("../../assets/Bank/SBI.png"),
  MOBIKWIK: require("../../assets/Bank/Mobikwik.png"),
  PAYTM: require("../../assets/Bank/Paytm.png"),
};

export default IMAGES;